version: '3'
services:
  legacy-project-processor:
    image: legacy-project-processor:latest
    container_name: legacy-project-processor
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - api.env
    volumes:
      - "../.nyc_output:/app/.nyc_output"
      - "../coverage:/app/coverage"
    network_mode: "host"
    # command: run start
    # command: run test
    command: run test:cov
